openapi: '3.0.2'
info:
  title: LiveCode API
  version: '1.1'
paths:            
  /api/livecodes:    
    post:
      description: create new livecode
      requestBody:
        $ref: "#/components/schemas/LiveCodeExtendedMetadata"
      responses:
        '201':
          description: empty live code tutorial created, with this author
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LiveCodeExtendedMetadata"        
        '400': 
          description: invalid parameters (git, name, desc.)  
        '403':
          description: Unauthorized (not autheticated)        
    get:
      description: get all livecodes      
      parameters:
        - name: authorname
          schema:
            type: string
          in: query                      
          required: false
          description: name of the author
      responses:
        '200':
          description: list of live code metadata for list view
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/LiveCodeThumbnail"
  /api/livecodes/{livecode_id}:
    put:
      description: Update the LiveCodeExtendedMetadata name
      parameters:
        - in: path
          name: livecode_id
          required: true
          schema:
            type: string  
            format: mongo object-id
      requestBody:                      
        $ref: "#/components/schemas/LiveCodeBaseMetadata"
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LiveCodeExtendedMetadata"
        '404':
          description: wrong id          
        '400':
          description: Git metadata, name, or description is invalid       
        '403':
          description: Unauthorized (not yours)
    delete:
      description: Delete the livecode.
      parameters:
        - in: path
          name: livecode_id
          required: true
          schema:
            type: string  
      responses:
        '204':
          description: Deleted 
        '404':
          description: wrong id    
        '403':
          description: Unauthorized (not yours)
    get: 
      description: Get the live code data to show
      parameters:
        - in: path
          name: livecode_id
          schema: 
            type: string
          required: true
      responses:
        '200':
          description: succesfully retrived the live code metadata.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LiveCodeExtendedMetadata"
        '404':
          description: not found
        '403':
          description: Unauthorized (not yours or not published)
components: 
  schemas:        
    GitMetadata:
      type: object
      required:
        - "repository_url"
        - "branch_name"
      properties:
        repository_url:
          type: string
        branch_name:
          type: string  
    LiveCodeBaseMetadata:
      type: object      
      required:
        - "name"
        - "description"
        - "git"    
      properties:  
        id:
          readOnly: true
          type: string
          format: uuid        
        git:                      
          $ref: "#/components/schemas/GitMetadata"    
        name:
          type: string
        description:
          type: string
        video_length: 
          type: integer
          format: int32
          default: -1  
          readOnly: true
        finalized:
          type: boolean
          default: false
        published:
          type: boolean 
          default: false     
    LiveCodeThumbnail:
      type: object
      allOf:
        - $ref: "#/components/schemas/LiveCodeBaseMetadata"        
      required:
        - "name"
        - "description"
        - "git"        
      properties:
        thumbnail_url:
          readOnly: true
          type: string      
    LiveCodeExtendedMetadata:
      type: object      
      allOf:
        - $ref: "#/components/schemas/LiveCodeBaseMetadata"
      required:
        - "name"
        - "description"
        - "git"          
      properties:        
        code_changes:
          readOnly: true
          description: an array of code changes, ordered by seconds_elpaseds elapsed number. 
            The first item will have seconds_elpased elapsed number 0. 
            on each seconds_elpased where significant code change was recorded, 
            there will be entry describing that code change.
          type: array
          items:
            properties:
              commit:
                type: string
        video_versions:          
          readOnly: true
          description: an array of available video versions.
            it is possible that no version was created yet.            
          type: array
          items: 
            properties:
              url:
                type: string